# -*- coding: utf-8 -*-
"""atividade6 mecanismos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irS-dWE0tUSFpxxxd8CkiZwMME-E4rwY
"""

from numpy import pi, arctan2, sqrt, cos, sin, radians, arctan

a = 127
b = 177.8
c = 152.4
d = 203.2
theta2 = 25
w2 = 24
alfa2 = -4
delta3 = 45
RPA = 127

k1 = d/a
k2 = d/c
k3 = ( (a**2) - (b**2) + (c**2) + (d**2) )/(2*a*c)
k4 = d/b
k5 = ( (c**2) - (d**2) - (a**2) - (b**2) )/(2*a*b)

A = cos(radians(theta2)) - k1 - (k2*cos(radians(theta2))) + k3
B = -2*sin(radians(theta2))
C = k1 - (k2 + 1)*cos(radians(theta2)) + k3
D = cos(radians(theta2)) - k1 + k4*cos(radians(theta2)) + k5
E = -2*sin(radians(theta2))
F = k1 + (k4 - 1)*cos(radians(theta2)) + k5


x = 2*arctan2(-B-sqrt( (B**2) - 4*A*C ), 2*A)*180/pi

theta4 =  x + 360

j = 2*arctan2(-E-sqrt( (E**2) - 4*D*F ), 2*D)*180/pi

theta3 =  j + 360

w3= ((a*w2)/b) * sin( radians(theta4 - theta2) ) / sin( radians(theta3 - theta4) )  
w4= ( (a*w2) / c) * sin( radians(theta2 - theta3 ) ) / sin( radians(theta4 - theta3) )

AAx = -a*alfa2 * cos( radians(theta2) ) - a * (w2**2) * cos(radians(theta2)) 
AAy = a*alfa2 * cos( radians(theta2) ) - a * (w2**2) * sin(radians(theta2)) 

AA1 = sqrt( (AAx**2) + (AAy**2) )

thetaAA = arctan2(AAy, AAx)*180/pi

A1=c*sin( radians(theta4) )   
B1=b*sin( radians(theta3) )      
D1=c*cos( radians(theta4) )    
E1=b*cos( radians(theta3) )

C1 = a * alfa2 * sin( radians(theta2) ) + a*(w2**2) * cos( radians(theta2) ) + b*(w3**2) * cos( radians(theta3)) -  c*(w4**2) * cos( radians(theta4))
F1 = a * alfa2 * cos( radians(theta2) ) - a*(w2**2) * sin( radians(theta2) ) - b*(w3**2) * sin( radians(theta3)) +  c*(w4**2) * sin( radians(theta4))

alfa3 = (C1*D1 - A1*F1) / (A1*E1 - B1*D1)
alfa4 = (C1*E1 - B1*F1) / (A1*E1 - B1*D1)

ABx = c*( -alfa4 * sin( radians(theta4) ) - (w4**2) * cos( radians(theta4) ))
ABy = c*( alfa4 * cos( radians(theta4) ) - (w4**2) * sin( radians(theta4) ))

AB = sqrt( (ABx**2) + (ABy**2) )

thetaAB = arctan2(ABy, ABx)*180/pi

AA = a*alfa2 * (-sin( radians(theta2) ) + cos( radians(theta2) ) ) - a*(w2**2) * (cos( radians(theta2) ) + sin( radians(theta2) ) )
APA = RPA * alfa3 * ( -sin( radians(theta3 + delta3 ) ) + cos( radians(theta3 + delta3 ) ) )  + RPA * (w3**2) * (cos( radians(theta3 + delta3 ) + sin( radians(theta3 + delta3 ) )))

AP = APA + AA

AP1 = sqrt(AP**2)

thetaAP = arctan(AP)*180/pi


print('theta3={:.3f}, theta4={:.3f}' .format(theta3, theta4))
print('w3={:.3f}, w4={:.3f}' .format(w3, w4))
print('AA={:.3f}, thetaAA={:.3f}' .format(AA1, thetaAA))
print('alfa3={:.3f}, alfa4={:.3f}' .format(alfa3, alfa4))
print('AB={:.3f}, thetaAB={:.3f}' .format(AB, thetaAB))
print('AA1={:.3f}, APA={:.3f}' .format(AA, APA))
print('AP={:3f}, thetaAP={:.3f}' .format(AP1, thetaAP))